[package]
name = "hashcode_score_calc"
version = "0.1.0"
authors = ["ori <oriashur155@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.11"
itertools = "0.9.0"
nom = "5.1.1"
